config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :profiles
  resources :github_repositories do
    resource :github_repository_monitoring_configurations
  end
  resources :github_accounts do
    get :swagger, on: :collection
  end
  resources :github_hook_events
  resources :users do
    get :swagger, on: :collection
  end
  # TODO: rails cant figure out custom login routes with swagger on like this... need to figure out
  # resources :sessions do
  #   get :swagger, on: :collection
  # end
  get 'home/index'
  post 'github_webhooks/payload'
  post 'github_repositories/sync'
  patch '/subscription' => 'subscriptions#update'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'home#index'
end

app/models/github_repository_monitoring_configuration.rb
class GithubRepositoryMonitoringConfiguration < ApplicationRecord
  belongs_to :github_repository
  has_one :github_account, through: :github_repository
  has_one :github_hook, through: :github_repository
  has_many :monitoring_contributors, class_name: 'GithubRepositoryMonitoringContributor', foreign_key: :github_repository_monitoring_configuration_id

  NOTIFICATION_TYPES = %w[
    commit_comment discussion discussion_comment issue_comment
    pull_request pull_request_review pull_request_review_comment
  ].freeze

  validate :validate_notification_types

  def validate_notification_types
    return if (notification_types - NOTIFICATION_TYPES).empty?

    errors.add(:notification_types, 'one or more types invalid')
  end

end

app/controllers/github_repository_monitoring_configurations_controller.rb
class GithubRepositoryMonitoringConfigurationsController < ApplicationController
  load_and_authorize_resource

  # GET /github_repository_monitoring_configurations or /github_repository_monitoring_configurations.json
  def index
    @github_repository_monitoring_configurations = GithubRepositoryMonitoringConfiguration.all
  end

  # GET /github_repository_monitoring_configurations/1 or /github_repository_monitoring_configurations/1.json
  def show
  end

  # GET /github_repository_monitoring_configurations/new
  def new
    @github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.new
    @github_repository = GithubRepository.find(params[:github_repository_id])
  end

  # GET /github_repository_monitoring_configurations/1/edit
  def edit
    @github_repository = GithubRepository.find(params[:github_repository_id])
  end

  define :post, :create, ' github_repositories/{id}/github_repository_monitoring_configurations' do
    summary 'Create a monitoring configuration for a github repository.'
    description <<~MARKDOWN
      You can use this endpoint to create a GithubRepositoryMonitoringConfiguration record.
    MARKDOWN
    path_params { attribute :github_repository_id, Types::Params::Integer }
    request_body do
      attribute :github_repository_monitoring_configuration do
        attribute :github_repository_id, Types::Params::Integer
        attribute :notification_types, Types::Params::Array
        attribute? :contributors_to_monitor do
          attribute :ids, SoberSwag::Types::Array.of(Types::Params::String)
        end
      end
    end
  end
  def create
    create_params = parsed_body.to_h[:github_repository_monitoring_configuration]

    # filter out empty strings
    create_params.tap do |params|
      params[:notification_types] = params[:notification_types].reject(&:empty?)
      params[:contributors_to_monitor][:ids] = params[:contributors_to_monitor][:ids].reject(&:empty?) if params.key?(:contributors_to_monitor)
    end

    result = GithubRepositoryMonitoringConfigurationCreator.new(create_params).call

    respond_to do |format|
      if result.success?
        redirect = github_repository_github_repository_monitoring_configurations_path(
          result.data.github_repository,
          id: result.data
        )

        format.html { redirect_to redirect, notice: "Github repository monitoring configuration was successfully created." }
        format.json { render :show, status: :created, location: result }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_repository_monitoring_configurations/1 or /github_repository_monitoring_configurations/1.json
  def update
    respond_to do |format|
      if @github_repository_monitoring_configuration.update(github_repository_monitoring_configuration_params)
        format.html { redirect_to @github_repository_monitoring_configuration, notice: "Github repository monitoring configuration was successfully updated." }
        format.json { render :show, status: :ok, location: @github_repository_monitoring_configuration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @github_repository_monitoring_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_repository_monitoring_configurations/1 or /github_repository_monitoring_configurations/1.json
  def destroy
    @github_repository_monitoring_configuration.destroy
    respond_to do |format|
      format.html { redirect_to github_repository_monitoring_configurations_url, notice: "Github repository monitoring configuration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_repository_monitoring_configuration
      @github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def github_repository_monitoring_configuration_params
      params.require(:github_repository_monitoring_configuration).permit(:github_repository_id, notification_types: [])
    end
end

app/helpers/github_repository_monitoring_configurations_helper.rb
module GithubRepositoryMonitoringConfigurationsHelper
end

app/views/github_repository_monitoring_configurations/_form.html.erb
<%= form_with(model: [@github_repository, @github_repository_monitoring_configuration]) do |form| %>
  <% if @github_repository_monitoring_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@github_repository_monitoring_configuration.errors.count, "error") %> prohibited this github_repository_monitoring_configuration from being saved:</h2>

      <ul>
        <% @github_repository_monitoring_configuration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label 'Select the type of notifications you want to receive', class: 'form-label' %>
    <%= form.select :notification_types, GithubRepositoryMonitoringConfiguration::NOTIFICATION_TYPES, { }, multiple: true, class: 'selectpicker form-control', 'multiple data-selected-text-format': 'count', 'data-width':'fit' %>
  </div>

  <% if @github_repository.contributors.any? %>
    <%= form.fields_for :contributors_to_monitor do |contributors_form| %>
      <div class="form-group">
        <%= contributors_form.label 'Select the users whom you would like to receive notifications from', class: 'form-label' %>
        <%= contributors_form.select :ids, options_from_collection_for_select(@github_repository.contributors, 'id', 'login'), {}, multiple: true, class: 'selectpicker form-control', 'multiple data-selected-text-format': 'count', 'data-width':'fit' %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :github_repository_id, value: params[:github_repository_id] %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Monitoring Configuration', class:"btn btn-success" %>
  </div>
<% end %>

app/views/github_repository_monitoring_configurations/edit.html.erb
<h1>Editing Github Repository Monitoring Configuration</h1>

<%= render 'form', github_repository_monitoring_configuration: @github_repository_monitoring_configuration %>

<%= link_to 'Show', @github_repository_monitoring_configuration %> |
<%= link_to 'Back', github_repository_monitoring_configurations_path %>

app/views/github_repository_monitoring_configurations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Github Repository Monitoring Configurations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @github_repository_monitoring_configurations.each do |github_repository_monitoring_configuration| %>
      <tr>
        <td><%= link_to 'Show', github_repository_monitoring_configuration %></td>
        <td><%= link_to 'Destroy', github_repository_monitoring_configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github Repository Monitoring Configuration', new_github_repository_monitoring_configuration_path %>

app/views/github_repository_monitoring_configurations/new.html.erb
<h1>Monitoring Configuration for <b><%=@github_repository.name %></b></h1>

<%= render 'form', github_repository_monitoring_configuration: @github_repository_monitoring_configuration %>

app/views/github_repository_monitoring_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1> Monitoring Configuration for Repository: <%= @github_repository_monitoring_configuration.github_repository.name %>
</div>
<div>
  <h2>Currently Monitoring</h2>
      <% @github_repository_monitoring_configuration.notification_types.each do |type| %>
        <p><%= type %></p>
      <% end %>
</div>

<%= link_to 'Profile', profile_path(@github_repository_monitoring_configuration.github_account.user.profile) %>