config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :profiles
  resources :github_repositories do
    resource :github_repository_monitoring_configurations
  end
  resources :github_accounts do
    get :swagger, on: :collection
  end
  resources :github_hook_events
  resources :users do
    get :swagger, on: :collection
  end
  # TODO: rails cant figure out custom login routes with swagger on like this... need to figure out
  # resources :sessions do
  #   get :swagger, on: :collection
  # end
  get 'home/index'
  post 'github_webhooks/payload'
  post 'github_repositories/sync'
  patch '/subscription' => 'subscriptions#update'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'home#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :github_repositories, through: :user
  has_one :github_account, through: :user

  def name
    user.name
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @github_repositories = @profile.github_repositories
    @github_account = @profile.github_account
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.fetch(:profile, {})
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%= javascript_pack_tag 'profiles' %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <div>
      <h1> <%= @profile.name %> </h1>
    </div>

    <div>
      <div>
        <%= image_tag @profile.github_account.avatar_url %>
      </div>
      <div id="profile-details">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">  <b> Github Account: </b> <%= link_to @profile.github_account.login, @profile.github_account.html_url %> </li>
          <li class="list-group-item"> <b> Location: </b> <%= @profile.github_account.location %> </li>
          <li class="list-group-item"> <b> Company: </b> <%= @profile.github_account.company %> </li>
          <li class="list-group-item"> <b> Bio: </b> <%= @profile.github_account.bio %> </li>
          <li class="list-group-item"> <%= link_to 'Edit Profile', edit_profile_path(@profile) %> </li>
          <li class="list-group-item"> <%= link_to 'Log Out', logout_path, method: :delete %> </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="profile-repositories">
      <div class="profile-repositories-header">
        <h1>Monitoring Github Repositories</h1>
      </div>
      <div class="profile-repositories-body">
        <div id="profile-repositories-btn-container">
          <button onclick="location.href='/github_repositories'" class="btn btn-primary"> Manage Repositories </button>
        </div>

        <ul class="list-group">
          <% @profile.github_repositories.monitoring.each do |repo| %>
            <li class="list-group-item list-group-item-action list-group-item-primary"> <%= link_to repo.name, repo.html_url %> </li>
            <ul class="list-group">
              <li class="list-group-item list-group-item-action list-group-item-danger"> <b> Actions: </b> <%= repo&.monitoring_configuration&.notification_types %> </li>
              <li class="list-group-item list-group-item-action list-group-item-warning"> <%= link_to 'Edit Monitoring Settings', edit_github_repository_path(repo) %> </li>
            </ul>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-4">
    <div id="profile-github-events">
      <div id="profile-github-events-header">
        <h1> Github Events Feed </h1>
      </div>
      <div id="profile-github-events-body">
        <% if @profile.github_account.events.any? %>
          <button onclick="location.href='/github_hook_events'" class="btn btn-secondary">All Events</button>
          <% @profile.github_account.events.order(created_at: :desc).limit(5).each do |event| %>
            <ul class="list-group">
              <li class="list-group-item"> Event Type: <%= event.type %> </li>
              <li class="list-group-item"> Action: <%= event.action %> </li>
              <li class="list-group-item"> At: <%= event.created_at %> </li>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>