config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :profiles
  resources :github_repositories do
    resource :github_repository_monitoring_configurations
  end
  resources :github_accounts do
    get :swagger, on: :collection
  end
  resources :github_hook_events
  resources :users do
    get :swagger, on: :collection
  end
  # TODO: rails cant figure out custom login routes with swagger on like this... need to figure out
  # resources :sessions do
  #   get :swagger, on: :collection
  # end
  get 'home/index'
  post 'github_webhooks/payload'
  post 'github_repositories/sync'
  patch '/subscription' => 'subscriptions#update'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'home#index'
end

app/models/github_account.rb
class GithubAccount < ApplicationRecord
  belongs_to :user
  has_many :github_repositories
  has_many :github_hooks, through: :github_repositories
  has_many :events, through: :github_hooks

  validates :user_id, uniqueness: true
  validates :token, presence: true

  METADATA_ATTRS = %w[
    bio url blog name email
    login company html_url
    location avatar_url
  ].freeze

  METADATA_ATTRS.each do |attribute|
    define_method attribute do
      metadata[attribute]
    end
  end

  def github_id
    metadata['id']
  end

end

app/controllers/github_accounts_controller.rb
class GithubAccountsController < ApplicationController
  load_and_authorize_resource

  # GET /github_accounts or /github_accounts.json
  def index
    @github_accounts = GithubAccount.all
  end

  # GET /github_accounts/1 or /github_accounts/1.json
  def show
  end

  # GET /github_accounts/new
  def new
    @github_account = GithubAccount.new
  end

  # GET /github_accounts/1/edit
  def edit
  end

  define :post, :create, ' /github_accounts' do
    summary 'Create github account.'
    description <<~MARKDOWN
      You can use this endpoint to create a GithubAccount record.
      This resource must always be associated with a User.
    MARKDOWN
    request_body do
      attribute :github_account do
        attribute :user_id, Types::Params::Integer
        attribute :token, Types::Params::String
        attribute? :metadata, Types::Params::Hash
      end
    end
  end

  def create
    result = GithubAccountCreator.new(parsed_body.to_h[:github_account]).call
    @github_account = result.success? ? result.data : GithubAccount.new

    respond_to do |format|
      if result.success?
        format.html { redirect_to profile_path(@github_account.user.profile.id), notice: "Github account was successfully created." }
        format.json { render :show, status: :created, location: @github_account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_accounts/1 or /github_accounts/1.json
  def update
    respond_to do |format|
      if @github_account.update(github_account_params)
        format.html { redirect_to @github_account, notice: "Github account was successfully updated." }
        format.json { render :show, status: :ok, location: @github_account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @github_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_accounts/1 or /github_accounts/1.json
  def destroy
    @github_account.destroy
    respond_to do |format|
      format.html { redirect_to github_accounts_url, notice: "Github account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_account
      @github_account = GithubAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def github_account_params
      params.require(:github_account).permit(:token, :metadata, :user_id)
    end
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/views/github_accounts/_form.html.erb
<%= form_with(model: github_account) do |form| %>
  <% if github_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(github_account.errors.count, "error") %> prohibited this github_account from being saved:</h2>

      <ul>
        <% github_account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: params[:user_id] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/github_accounts/edit.html.erb
<h1>Editing Github Account</h1>

<%= render 'form', github_account: @github_account %>

<%= link_to 'Show', @github_account %> |
<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Github Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Token</th>
      <th>Metadata</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @github_accounts.each do |github_account| %>
      <tr>
        <td><%= github_account.token %></td>
        <td><%= github_account.metadata %></td>
        <td><%= github_account.user_id %></td>
        <td><%= link_to 'Show', github_account %></td>
        <td><%= link_to 'Edit', edit_github_account_path(github_account) %></td>
        <td><%= link_to 'Destroy', github_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github Account', new_github_account_path %>

app/views/github_accounts/new.html.erb
<h1>New Github Account</h1>

<%= render 'form', github_account: @github_account %>

<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @github_account.token %>
</p>

<p>
  <strong>Metadata:</strong>
  <%= @github_account.metadata %>
</p>

<p>
  <strong>User:</strong>
  <%= @github_account.user_id %>
</p>

<%= link_to 'Edit', edit_github_account_path(@github_account) %> |
<%= link_to 'Back', github_accounts_path %>